[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:395 ************************ Test Product Compare 012 Is Start **************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:397 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:403 Hovering on the desktop option and Clicking on the show all desktop option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:405 Clicking on the product compare link on the search result page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:406 ************************* Verifying Test Product Compare 012 ****************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:409 Clicking on the home page link available on the breadcrumb
[31m[1mERROR   [0m Test_006_Product_Compare:test_product_compare.py:413 ********** Test Product Compare 012 Is Passed **********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:421 ************************ End Of Test Product Compare 012 **************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022EFED339B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1f428af19bf76ce40f3486641dd0f18b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022EFED33DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1f428af19bf76ce40f3486641dd0f18b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022EFED32E00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1f428af19bf76ce40f3486641dd0f18b