[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:394 ************************ Test Product Compare 012 Is Start **************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:396 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:402 Hovering on the desktop option and Clicking on the show all desktop option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:404 Clicking on the product compare link on the search result page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:405 ************************* Verifying Test Product Compare 012 ****************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:408 Clicking on the home page link available on the breadcrumb
[1m[31mERROR   [0m Test_006_Product_Compare:test_product_compare.py:412 ********** Test Product Compare 012 Is Passed **********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:420 ************************ End Of Test Product Compare 012 **************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B00D7C8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49459dc4b9432964de1fc2f86d0af1a2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B00D7D590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49459dc4b9432964de1fc2f86d0af1a2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B00D7DF20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49459dc4b9432964de1fc2f86d0af1a2