[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:398 ************************ Test Product Compare 012 Is Start **************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:400 Navigating to the base url
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:406 Hovering on the desktop option and Clicking on the show all desktop option
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:408 Clicking on the product compare link on the search result page
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:409 ************************* Verifying Test Product Compare 012 ****************************
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:412 Clicking on the home page link available on the breadcrumb
[31m[1mERROR   [0m Test_006_Product_Compare:test_product_compare.py:416 ********** Test Product Compare 012 Is Passed **********
[32mINFO    [0m Test_006_Product_Compare:test_product_compare.py:424 ************************ End Of Test Product Compare 012 **************************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151DA2D69C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/56d9e423d9edb730a918eaab7dd06549
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151DA2D4F30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/56d9e423d9edb730a918eaab7dd06549
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151DA2D5E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/56d9e423d9edb730a918eaab7dd06549